FROM ubuntu:16.04

# Use speedup source for Chinese Mainland user,if not you can remove it
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    && apt update \
    && apt upgrade -y

RUN apt-get update \
    && apt install -y python-pip curl clang git apt-transport-https ca-certificates gnupg2 software-properties-common cmake make automake wget jq zip unzip tree htop 


# Add apt key for LLVM repository
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    && echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main" | tee -a /etc/apt/sources.list

# Install clang from LLVM repository
RUN apt-get update && apt-get install -y --no-install-recommends  clang-6.0 clang-format-6.0 git

RUN apt autoremove \
    && apt clean

COPY protoc-gen-go /usr/bin/
COPY protoc /usr/bin/
COPY shellcheck /usr/bin/

RUN chmod +x /usr/bin/protoc-gen-go \
    && chmod +x /usr/bin/shellcheck \
    && chmod +x /usr/bin/protoc

# golang env
RUN curl -O https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz \
    && tar -zxvf go1.12.9.linux-amd64.tar.gz \
    && mv go /opt/

COPY install.sh /root/
RUN cd /root && bash install.sh


